# Generated by Django 3.1.6 on 2021-03-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogging',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
