# Generated by Django 3.1.6 on 2021-03-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210330_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogging',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogging',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogging',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
